# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d3417b3eaad79d881ec53a5f97e5eec"
name = "onchain-affiliate-v7"
handle = "onchain-affiliate-v7"
application_url = "https://bp-preventing-lowest-colors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "onchain-affiliate.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,read_metaobjects,read_orders,write_discounts"

[auth]
redirect_urls = [
  "https://bp-preventing-lowest-colors.trycloudflare.com/auth/callback",
  "https://bp-preventing-lowest-colors.trycloudflare.com/auth/shopify/callback",
  "https://bp-preventing-lowest-colors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
